/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#0c1321",
        "surface-dim": "#0c1321",
        "surface-bright": "#323949",
        "surface-container-lowest": "#070e1c",
        "surface-container-low": "#151b2a",
        "surface-container": "#19202e",
        "surface-container-high": "#232a39",
        "surface-container-highest": "#2e3544",
        "on-surface": "#dce2f6",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#dce2f6",
        "inverse-on-surface": "#2a3040",
        outline: "#8c909f",
        "outline-variant": "#424754",
        "surface-tint": "#adc6ff",
        primary: "#adc6ff",
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        secondary: "#4ae176",
        "on-secondary": "#003915",
        "secondary-container": "#00b954",
        "on-secondary-container": "#004119",
        tertiary: "#eec200",
        "on-tertiary": "#3c2f00",
        "tertiary-container": "#cea700",
        "on-tertiary-container": "#4e3e00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#0c1321",
        "on-background": "#dce2f6",
        "surface-variant": "#2e3544",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "hud-inset-desktop": "1.5rem",
        "hud-inset-mobile": "1rem",
        "drawer-width-desktop": "420px",
        "drawer-width-collapsed": "72px",
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(3, 7, 18, 0.45)",
        "glass-hover": "0 12px 40px -4px rgba(3, 7, 18, 0.65), 0 0 16px -2px rgba(59, 130, 246, 0.30)",
        "glass-modal": "0 24px 64px 0 rgba(0, 0, 0, 0.75), 0 0 24px 0 rgba(59, 130, 246, 0.25)",
        "glow-primary": "0 0 16px rgba(77, 142, 255, 0.35)",
        "glow-secondary": "0 0 12px rgba(74, 225, 118, 0.4)",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};
